language: node_js
node_js: node
sudo: required
addons:
  apt:
    packages:
    - wine
before_deploy:
- git config --local user.name "demosjarco"
- git config --local user.email "demosjarco@users.noreply.github.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: JIRLLJ271JrKGCqUihjaw0ppmnc1DeH3kFqn8QOJgCz+gVnr8kK+hXhLAJXULkvc7+X4G+QFFy+i3wws6mnVfz6nHEjQcAh2OQaTdzsxljQFEfeyZaCyOW6v4lqSRN11oFMmWeAu/5Nh4rsfGyHFrC5YuXi64MotdbT44CCWI+N9IPTV04r4bzP6Rop12SXSFbYynhgzAVNeK/YS2YaNop0DWk1vjxjRtF//bT096xDOSZ4CwI7EaBTmLfJ8vWFS1ncbpVkK6rijeML1sh+RLZfnzcpbbzWNxH8haMdaSCpeySPVXBu5ytnuxgzCLaVCsRfXLHyJAmuuTuMB/TSSQon/Eqsufh+rw59uz6IpyRjYQ/6dl9LIODS7xq+jBkhacrUGmJuks43ljFcT9IJVj07TfE/ZdX8RIVWmiV4qjFL8LKvaq3H6DAtjyyczfyJ/qaV4/qw7qhmbDDFDHFL9pD/FjmpUv/4PqOdyOAAMHEIUuDjMUrboxsAmZpmOLQUYYDNKUa3l9AbnWdYXhumeHjx9UyuyWMvYjUUqNT/eWurkkphUf3cl+xihsQ2fZxoA96HxCAlHQw0PSoLEuhb6TWuhQchLFG7OSZrA/fr89muSdZq38HUzSiwtuZZi2MuRrtE/b6W6d41cTFg1fNZPUJvssclqJcWHewaAMSu41vk=
  file: overviewer-configurator-win32-x64.zip
  on:
    repo: demosjarco/overviewer-configurator
    branch: master
