name: builder
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: see directory
      run: ls
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: see directory
      run: ls