name: builder
on:
  push:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'
  pull_request:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install NodeJS (12.x)
      uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Uninstall unneeded dependencies
      run: npm uninstall electromon less less-watch-compiler -D
    - name: Delete dev files
      run: rm -fv css/*.less
    - name: Package electron
      run: npm run pack:osx
    - name: List different packages
      run: ls builds/packaged/
    - name: List finished package content
      run: ls builds/packaged/Overviewer*/
    - name: Install glob for release
      run: npm install glob -D
    - name: Upload to Beta Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/b')
      with:
        prerelease: true
        files: builds/packaged/Overviewer*/*.app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Final Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: builds/packaged/Overviewer*/*.app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_win:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install NodeJS (12.x)
      uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Uninstall unneeded dependencies
      run: npm uninstall electromon less less-watch-compiler -D
    - name: Delete dev files
      run: rm -fv css/*.less
    - name: Package electron
      run: npm run pack:win
    - name: Create Installer
      run: npm run inst:win
    - name: List different packages
      run: ls builds/packaged/
    - name: List finished package content
      run: ls builds/packaged/Overviewer*/
    - name: List finished installers
      run: ls builds/installers
    - name: Install glob for release
      run: npm install glob -D
    - name: Upload to Beta Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/b')
      with:
        prerelease: true
        files: builds/installers/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Final Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: builds/installers/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}