name: builder
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: see directory
      run: ls