name: builder
on:
  push:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'
  pull_request:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install
    - name: Uninstall unneeded dependencies
      run: npm uninstall electromon less less-watch-compiler -D
    - name: Delete dev files
      run: rm -fv css/*.less
    - run: npm run pack:osx
    - name: List different packages
      run: ls builds/packaged/
    - name: List finished package content
      run: ls builds/packaged/Overviewer*/
    - name: Install glob for release
      run: npm install glob -D
    - name: Upload to Beta Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/b')
      with:
        prerelease: true
        files: |
            builds/packaged/Overviewer Configurator-darwin-x64/Overviewer Configurator.app
            builds/packaged/Overviewer Configurator-darwin-x64/version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Final Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
            builds/packaged/Overviewer Configurator-darwin-x64/Overviewer Configurator.app
            builds/packaged/Overviewer Configurator-darwin-x64/version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install
    - name: Uninstall unneeded dependencies
      run: npm uninstall electromon less less-watch-compiler -D
    - name: Delete dev files
      run: rm -fv css/*.less
    - run: npm run pack:win
    - name: Compress package x32
      run: Compress-Archive builds\packaged\Overviewer Configurator-win32-ia32 Overviewer-Configurator-win32-ia32.zip
      shell: powershell
    - name: Compress package x64
      run: Compress-Archive builds\packaged\Overviewer Configurator-win32-x64 Overviewer-Configurator-win32-x64.zip
      shell: powershell
    - run: npm run inst:win
    - name: List different packages
      run: ls builds/packaged/
    - name: List finished package content
      run: ls builds/packaged/Overviewer*/
    - name: List finished installers
      run: ls builds/installers
    - name: Install glob for release
      run: npm install glob -D
    - name: Upload to Beta Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/b')
      with:
        prerelease: true
        files: |
            builds/installers/*
            Overviewer-Configurator-win32-ia32.zip
            Overviewer-Configurator-win32-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Final Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
            builds/installers/*
            Overviewer-Configurator-win32-ia32.zip
            Overviewer-Configurator-win32-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}