name: builder
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - uses: artemnovichkov/action-homebrew@master
    - name: Install dependencies
      run: npm install
    - name: Package electron
      run: npm run pack:osx
    - name: see directory
      run: ls
    - name: install tree
      run: brew install tree
    - name: see directory tree
      run: tree
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Package electron
      run: npm run pack:win
    - name: Create Installer
      run: npm run inst:win
    - name: see directory
      run: ls
    - name: see directory tree
      run: tree /f /a